apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "draino2.fullname" . }}-config
  labels:
    {{- include "draino2.labels" . | nindent 4 }}
data:
  draino2.yaml: |
    {{- toYaml .Values.config | nindent 4 }} 