apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: { { include "draino2.fullname" . } }
  labels: { { - include "draino2.labels" . | nindent 4 } }
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: { { include "draino2.fullname" . } }
  labels: { { - include "draino2.labels" . | nindent 4 } }
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: { { include "draino2.fullname" . } }
subjects:
  - kind: ServiceAccount
    name: { { include "draino2.serviceAccountName" . } }
    namespace: { { .Release.Namespace } }
